apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: wrak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: api
          image: ghcr.io/bluestack/orders-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: orders-configmap
          livenessProbe:
            httpGet:
              path: /health/deep
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/deep
              port: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "2"
              memory: "1Gi"
